### ISSUE TITLE
sphinx documentation under python 3 fails

### ISSUE THREAD

**Issue by aellery** [esys-escript/esys-escript.github.io#2] opened 2020-08-13 02:32 UTC
The sphinx documentation does not build properly when using the python 3 version of sphinxdocs. Partway through the build autodocs returns a KeyError.

`KeyError: 'Boost.Python'`

To reproduce, run

`scons -j8 sphinxdoc`

**Comment by LutzGross** [comment] 2022-06-08 07:08
duplicate of #56

**Closed by LutzGross** 2022-06-08 07:08 UTC
Labels: duplicate
